/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type Audit struct {
	Id string `json:"id,omitempty"`

	OrganizationId string `json:"organization_id,omitempty"`

	AccountId string `json:"account_id,omitempty"`

	Operation string `json:"operation,omitempty"`

	HttpCodeResult float32 `json:"http_code_result,omitempty"`

	Success string `json:"success,omitempty"`

	Message string `json:"message,omitempty"`

	IdentityEmail string `json:"identity_email,omitempty"`

	TargetResource string `json:"target_resource,omitempty"`

	TargetId string `json:"target_id,omitempty"`

	Body string `json:"body,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
