/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type BackupHits struct {
	Id string `json:"id,omitempty"`

	Type_ string `json:"Type,omitempty"`

	BackupId string `json:"BackupId,omitempty"`

	Tags []AmiRestoreRequestRestoreTags `json:"Tags,omitempty"`

	State string `json:"State,omitempty"`

	Size string `json:"Size,omitempty"`

	Progress string `json:"Progress,omitempty"`

	Region string `json:"Region,omitempty"`

	CreatedAt string `json:"CreatedAt,omitempty"`
}
