/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type BackupDetailOne struct {
	Description string `json:"Description,omitempty"`

	Encrypted string `json:"Encrypted,omitempty"`

	OwnerId string `json:"OwnerId,omitempty"`

	Progress string `json:"Progress,omitempty"`

	SnapshotId string `json:"SnapshotId,omitempty"`

	StartTime string `json:"StartTime,omitempty"`

	State string `json:"State,omitempty"`

	VolumeId string `json:"VolumeId,omitempty"`

	VolumeSize string `json:"VolumeSize,omitempty"`

	Tags []Tag `json:"Tags,omitempty"`

	OrganizationId string `json:"__OrganizationId,omitempty"`

	AccountId string `json:"__AccountId,omitempty"`

	PostDate string `json:"postDate,omitempty"`

	Region string `json:"Region,omitempty"`

	Type_ string `json:"Type,omitempty"`

	Source string `json:"Source,omitempty"`

	ObjectType string `json:"ObjectType,omitempty"`

	BackupTime string `json:"BackupTime,omitempty"`

	Id string `json:"Id,omitempty"`
}
