/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type Credential struct {
	AccountId string `json:"account_id,omitempty"`

	ExternalId string `json:"external_id,omitempty"`

	AccessRoleArn string `json:"access_role_arn,omitempty"`

	CloudformationS3Url string `json:"cloudformation_s3_url,omitempty"`

	State string `json:"state,omitempty"`

	StateReason string `json:"state_reason,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
