/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type Job struct {
	Id string `json:"id,omitempty"`

	Type_ string `json:"type,omitempty"`

	EventType string `json:"eventType,omitempty"`

	ObjectId float32 `json:"object_id,omitempty"`

	Cron string `json:"cron,omitempty"`

	TotalTasks float32 `json:"totalTasks,omitempty"`

	TotalSuccess float32 `json:"totalSuccess,omitempty"`

	TotalFail float32 `json:"totalFail,omitempty"`

	Date string `json:"date,omitempty"`

	EventAt string `json:"event_at,omitempty"`

	Seq float32 `json:"seq,omitempty"`

	Tasks []JobTask `json:"tasks,omitempty"`
}
