/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type JobTask struct {
	Id string `json:"id,omitempty"`

	JobId string `json:"job_id,omitempty"`

	Region string `json:"region,omitempty"`

	ResourceType string `json:"resource_type,omitempty"`

	ResourceId string `json:"resource_id,omitempty"`

	ResourceName string `json:"resource_name,omitempty"`

	Action string `json:"action,omitempty"`

	IsSuccess string `json:"is_success,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`

	Logs []Empty `json:"logs,omitempty"`

	Steps []JobTaskStep `json:"steps,omitempty"`
}
