/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type Schedule struct {
	Id float32 `json:"id,omitempty"`

	ScheduleId float32 `json:"schedule_id,omitempty"`

	OrganizationId string `json:"organization_id,omitempty"`

	AccountId string `json:"account_id,omitempty"`

	TimezoneLocation string `json:"timezone_location,omitempty"`

	Name string `json:"name,omitempty"`

	Type_ string `json:"type,omitempty"`

	PercentOn float32 `json:"percent_on,omitempty"`

	HoursOn float32 `json:"hours_on,omitempty"`

	Description string `json:"description,omitempty"`

	ScheduleJson string `json:"schedule_json,omitempty"`

	IsActive bool `json:"is_active"`

	MatchAllTagsFlag bool `json:"match_all_tags_flag"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`

	DeletedAt string `json:"deleted_at,omitempty"`

	Tags []Tag `json:"tags,omitempty"`

	Servers []Server `json:"servers,omitempty"`
}
