/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type ServerPolicy struct {
	Id float32 `json:"id,omitempty"`

	OrganizationId string `json:"organization_id,omitempty"`

	AccountId string `json:"account_id,omitempty"`

	TimezoneLocation string `json:"timezone_location,omitempty"`

	Name string `json:"name,omitempty"`

	CreateSummary string `json:"create_summary,omitempty"`

	DeleteSummary string `json:"delete_summary,omitempty"`

	Description string `json:"description,omitempty"`

	BackupSource string `json:"backup_source,omitempty"`

	BackupTarget string `json:"backup_target,omitempty"`

	InheritTags string `json:"inherit_tags,omitempty"`

	PerformConsistentSnapshots string `json:"perform_consistent_snapshots,omitempty"`

	PerformReboot string `json:"perform_reboot,omitempty"`

	RetentionAmount float32 `json:"retention_amount,omitempty"`

	RetentionUnit string `json:"retention_unit,omitempty"`

	RetentionInHours float32 `json:"retention_in_hours,omitempty"`

	RetentionInDays string `json:"retention_in_days,omitempty"`

	NeverDelete string `json:"never_delete,omitempty"`

	CreateCron string `json:"create_cron,omitempty"`

	BackupOriginalRegionFlag string `json:"backup_original_region_flag,omitempty"`

	BackupSecondRegionFlag string `json:"backup_second_region_flag,omitempty"`

	BackupSecondRegion string `json:"backup_second_region,omitempty"`

	BackupThirdRegionFlag string `json:"backup_third_region_flag,omitempty"`

	BackupThirdRegion string `json:"backup_third_region,omitempty"`

	FirstCrossAccountFlag string `json:"first_cross_account_flag,omitempty"`

	FirstCrossAccountAccountId string `json:"first_cross_account_account_id,omitempty"`

	FirstCrossAccountRegion string `json:"first_cross_account_region,omitempty"`

	IsActive string `json:"is_active,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`

	DeletedAt string `json:"deleted_at,omitempty"`

	Tags []Tag `json:"tags,omitempty"`
}
