/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type Setting struct {
	AccountId string `json:"account_id,omitempty"`

	SendBackupNotifications bool `json:"send_backup_notifications,omitempty"`

	SendServerNotifications bool `json:"send_server_notifications,omitempty"`

	SendFailureNotifications bool `json:"send_failure_notifications,omitempty"`

	SendWarningNotifications bool `json:"send_warning_notifications,omitempty"`

	BackupRecipientsJson string `json:"backup_recipients_json,omitempty"`

	ServerRecipientsJson string `json:"server_recipients_json,omitempty"`

	FailureRecipientsJson string `json:"failure_recipients_json,omitempty"`

	WarningRecipientsJson string `json:"warning_recipients_json,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
