/*
 * CloudRanger API
 *
 *  # Welcome to CloudRanger  Here are some instructions on  how to use the API  ## Authentication and Authorization   * Access to the API is controlled by your API key generated in the CloudRanger dashboard and token  * The token is returned by calling the /authorize endpoint and supplying the x-api-key header  * All other calls use the x-api-key header and the Authorzation header with Bearer followed by your token
 *
 * API version: 2018-05
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloudranger

type WeeklySaving struct {
	Monday string `json:"Monday,omitempty"`

	Tuesday string `json:"Tuesday,omitempty"`

	Wednesday string `json:"Wednesday,omitempty"`

	Thursday string `json:"Thursday,omitempty"`

	Friday string `json:"Friday,omitempty"`

	Saturday string `json:"Saturday,omitempty"`

	Sunday string `json:"Sunday,omitempty"`
}
